version: '3.7'

services:
  main:
    image: rivnd/backend:dev
    container_name: main
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4000:4000"